[package]
name = "image_test_dll"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hackers = { path = "../.." }
abi_stable = "0.11"
image = "0.25.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
